### ISSUE TITLE
Minor typos in some TLP posts

### ISSUE THREAD

**Issue by sainaen** [gigiigig/blog#1]
In _Phantom Types_ post, 1st paragraph:

> We have seen before how using Dependent Types we can do some really basic computations, however to do something actually useful we need more **that** that, …

In _Implicit Resolutions_, 3rd paragraph from the bottom:

> **Le** us see what happens when we call…

In _Implicitly and Type Equality_:

> Before proceeding you need to **now** how to use…

// I'd open a PR with fixes, but for some reason it feels a bit weird (rude?) to propose edits to someone else's blog without even asking first.
## 

Enjoyed the series, thanks for sharing! Hope you'll continue at some point (no pressure though :)

**Comment by gigiigig** [comment]
Hi  @sainaen sorry I've just seen this, feel free to open a PR, I'd be very happy!  :wink:

**Comment by sainaen** [comment]
No worries, opened #3.
